### ISSUE TITLE
Use eslint:recommended preset

### ISSUE THREAD

**Issue by kristoforsalmin** [kraftvaerk/eslint-config-kraftvaerk#10]
Hi there, I think it'd make sense to use [`eslint:recommended` preset](https://eslint.org/docs/rules/) as a base for our config. We'll get a set of sensible defaults, so less stuff for us to maintain. What do you think?

It probably makes sense to do #3 and #4 alongside with this one, if we have a go.

Thanks 😄

**Comment by mi2oon** [comment]
@racse1 If possible I surely think we should use the eslint recommended preset config as our base. However, I would like most of the rules we have as they are. So one would have to compare our config with what the recommended config brings in as default and remove what is not needed. Let me know if you start doing that.. otherwise, I might have the in the coming weekend ;)

**Comment by kristoforsalmin** [comment]
@mi2oon Cool, feel free to proceed 👍 If I were to start doing this one, that will probably be no sooner than the sometime next week. Otherwise I'll let you know 😄
