### ISSUE TITLE
Trailing comma

### ISSUE THREAD

**Issue by OneTwo7** [kraftvaerk/eslint-config-kraftvaerk#18]
As said in MDN [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas):

> Trailing commas (sometimes called "final commas") can be useful when adding new elements, parameters, or properties to JavaScript code. If you want to add a new property, you can simply add a new line without modifying the previously last line if that line already uses a trailing comma. This makes version-control diffs cleaner and editing code might be less troublesome.

Therefore, I propose we change [comma-dangle](https://eslint.org/docs/rules/comma-dangle) rule to require trailing commas, or at least not show an error when there isn't one. Any thoughts?

**Comment by kristoforsalmin** [comment]
Hi @OneTwo7, I'm definitely in favor of this one 👍 Also, it's more or less widely used since Airbnb's ESLint config requires trailing commas too. @mi2oon? 😄

**Comment by mi2oon** [comment]
@OneTwo7 @racse1 I also agree.. it's was relevant earlier due to older browsers throwing errors but I think we are safe now and if it gives cleaner diffs.. it's just a win win 👍   

Unfortunately the JSON specification does not allow a trailing comma. There are a few browsers that will allow it, but generally you need to worry about all browsers and therefore one could argue that for the sake of consistency we should keep the rule.

**Comment by kristoforsalmin** [comment]
Any other inputs from @kraftvaerk/frontend?

**Comment by kristoforsalmin** [comment]
As there were no comments the rule will be added to our config 🎉
